name: uts_4_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  get: 4.6.5
  google_sign_in: ^6.0.2
  pinput: ^2.2.31

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/Google.png
